// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/saremox/redis-operator/api/redisfailover/v1"
	service "github.com/saremox/redis-operator/operator/redisfailover/service"
)

// RedisFailoverHeal is an autogenerated mock type for the RedisFailoverHeal type
type RedisFailoverHeal struct {
	mock.Mock
}

// ApplyPassword provides a mock function with given fields: rFailover, password, previous
func (_m *RedisFailoverHeal) ApplyPassword(rFailover *v1.RedisFailover, password string, previous string) (bool, error) {
	ret := _m.Called(rFailover, password, previous)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, string) (bool, error)); ok {
		return rf(rFailover, password, previous)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, string) bool); ok {
		r0 = rf(rFailover, password, previous)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover, string, string) error); ok {
		r1 = rf(rFailover, password, previous)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApplySentinelPassword provides a mock function with given fields: rFailover, password
func (_m *RedisFailoverHeal) ApplySentinelPassword(rFailover *v1.RedisFailover, password string) (bool, error) {
	ret := _m.Called(rFailover, password)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string) (bool, error)); ok {
		return rf(rFailover, password)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string) bool); ok {
		r0 = rf(rFailover, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover, string) error); ok {
		r1 = rf(rFailover, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePod provides a mock function with given fields: podName, rFailover
func (_m *RedisFailoverHeal) DeletePod(podName string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(podName, rFailover)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(podName, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnsureRedisMaxMemory provides a mock function with given fields: rFailover, master, redises
func (_m *RedisFailoverHeal) EnsureRedisMaxMemory(rFailover *v1.RedisFailover, master string, redises []string) (service.MaxMemoryResult, error) {
	ret := _m.Called(rFailover, master, redises)

	var r0 service.MaxMemoryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, []string) (service.MaxMemoryResult, error)); ok {
		return rf(rFailover, master, redises)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, []string) service.MaxMemoryResult); ok {
		r0 = rf(rFailover, master, redises)
	} else {
		r0 = ret.Get(0).(service.MaxMemoryResult)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover, string, []string) error); ok {
		r1 = rf(rFailover, master, redises)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeMaster provides a mock function with given fields: ip, rFailover
func (_m *RedisFailoverHeal) MakeMaster(ip string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(ip, rFailover)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(ip, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSentinelMonitor provides a mock function with given fields: ip, monitor, rFailover
func (_m *RedisFailoverHeal) NewSentinelMonitor(ip string, monitor string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(ip, monitor, rFailover)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *v1.RedisFailover) error); ok {
		r0 = rf(ip, monitor, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSentinelMonitorWithPort provides a mock function with given fields: ip, monitor, port, rFailover
func (_m *RedisFailoverHeal) NewSentinelMonitorWithPort(ip string, monitor string, port string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(ip, monitor, port, rFailover)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, *v1.RedisFailover) error); ok {
		r0 = rf(ip, monitor, port, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResizePodInPlace provides a mock function with given fields: rFailover, podName, updateRevision
func (_m *RedisFailoverHeal) ResizePodInPlace(rFailover *v1.RedisFailover, podName string, updateRevision string) (service.ResizeResult, error) {
	ret := _m.Called(rFailover, podName, updateRevision)

	var r0 service.ResizeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, string) (service.ResizeResult, error)); ok {
		return rf(rFailover, podName, updateRevision)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, string) service.ResizeResult); ok {
		r0 = rf(rFailover, podName, updateRevision)
	} else {
		r0 = ret.Get(0).(service.ResizeResult)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover, string, string) error); ok {
		r1 = rf(rFailover, podName, updateRevision)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestoreSentinel provides a mock function with given fields: ip
func (_m *RedisFailoverHeal) RestoreSentinel(ip string) error {
	ret := _m.Called(ip)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetExternalMasterOnAll provides a mock function with given fields: masterIP, masterPort, rFailover
func (_m *RedisFailoverHeal) SetExternalMasterOnAll(masterIP string, masterPort string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(masterIP, masterPort, rFailover)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *v1.RedisFailover) error); ok {
		r0 = rf(masterIP, masterPort, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetMasterOnAll provides a mock function with given fields: masterIP, rFailover
func (_m *RedisFailoverHeal) SetMasterOnAll(masterIP string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(masterIP, rFailover)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(masterIP, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetOldestAsMaster provides a mock function with given fields: rFailover
func (_m *RedisFailoverHeal) SetOldestAsMaster(rFailover *v1.RedisFailover) error {
	ret := _m.Called(rFailover)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) error); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetRedisCustomConfig provides a mock function with given fields: ip, rFailover
func (_m *RedisFailoverHeal) SetRedisCustomConfig(ip string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(ip, rFailover)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(ip, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetSentinelCustomConfig provides a mock function with given fields: ip, rFailover
func (_m *RedisFailoverHeal) SetSentinelCustomConfig(ip string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(ip, rFailover)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(ip, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PromoteBestReplica provides a mock function with given fields: newMasterIP, rFailover
func (_m *RedisFailoverHeal) PromoteBestReplica(newMasterIP string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(newMasterIP, rFailover)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(newMasterIP, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewRedisFailoverHeal interface {
	mock.TestingT
	Cleanup(func())
}

// NewRedisFailoverHeal creates a new instance of RedisFailoverHeal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRedisFailoverHeal(t mockConstructorTestingTNewRedisFailoverHeal) *RedisFailoverHeal {
	mock := &RedisFailoverHeal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
