apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    enabled: true
    replicas: 3
    exporter:
      enabled: true
      image: quay.io/oliver006/redis_exporter:v1.80.0-alpine
  redis:
    replicas: 3
    exporter: 
      enabled: true
      image: quay.io/oliver006/redis_exporter:v1.80.0-alpine
      args:
        - --web.telemetry-path
        - /metrics
      env:
        - name: REDIS_EXPORTER_LOG_FORMAT
          value: txt
